{"name": "test_fixture_zcc[cc_calculator_shuju0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6", "trace": "self = <cc_work.test_fixture_zcc.TestCal_cc_new object at 0x0000000003966940>, cc_calculator_func = <cc_work.calculator_cc.Calculator object at 0x0000000003966A58>, cc_calculator_shuju = [3, 2, 6]\n\n    @pytest.mark.run(order=1)\n    def test_fixture_zcc(self, cc_calculator_func, cc_calculator_shuju):\n        try:\n            result = cc_calculator_func.add(cc_calculator_shuju[0], cc_calculator_shuju[1])\n            print('这是测试用例1')\n            print(f'实际值为{result}')\n            print(f'预期值为{cc_calculator_shuju[2]}')\n            # assert result == cc_calculator_shuju[2]  写在else里才能断言成功\n        except Exception as e:\n            print(e)\n        else:\n>           assert result == cc_calculator_shuju[2]\nE           assert 5 == 6\n\ntest_fixture_zcc.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "d889210a-fe83-4999-9af5-4a82f5002d12-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cc_calculator_shuju", "value": "[3, 2, 6]"}], "start": 1609384402696, "stop": 1609384402699, "uuid": "b77ba605-8efc-4eba-9164-a2a26036d246", "historyId": "92353a20b314acf47c0534a74c30c40e", "testCaseId": "53c508109c33f2121310f004fb063ffe", "fullName": "test_fixture_zcc.TestCal_cc_new#test_fixture_zcc", "labels": [{"name": "suite", "value": "test_fixture_zcc"}, {"name": "subSuite", "value": "TestCal_cc_new"}, {"name": "host", "value": "admin-PC"}, {"name": "thread", "value": "12648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture_zcc"}]}